### ISSUE TITLE
Update 1.17.3 broke svelte version?

### ISSUE THREAD

**Issue by blobinabottle** [pd4d10/hashmd#226]
After updating I get this error in my svelte app:
Cannot find module '@icon-park/svg' imported from 'xx/node_modules/bytemd/svelte/editor.js'

If I rollback to 1.17.2 no issues.

Is there manual migration to do to use 1.17.3?

**Comment by pd4d10** [comment]
It seems caused by 0e28d3364a2d3bdb0895099648ebc34391baddcd. Could you please try v1.17.4?

**Comment by blobinabottle** [comment]
Yes it's fixed! Thanks a lot

**Comment by blobinabottle** [comment]
🚀
